name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: sou-hyou
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Copy test environment file
      - name: Setup test environment
        run: cp .env.test .env.local

      # Apollo Server 起動 (test environment)
      - name: Start Apollo Server
        run: pnpm --filter=server dev &
        working-directory: packages/server
        env:
          NODE_ENV: test
          PORT: 4001
          MONGODB_URI: mongodb://admin:password@localhost:27017/sou-hyou-test?authSource=admin
          CORS_ORIGIN: http://localhost:3001

      # Next.js 起動 (test environment)
      - name: Start Next.js
        run: pnpm --filter=web dev &
        working-directory: apps/web
        env:
          NODE_ENV: test
          PORT: 3001
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://localhost:4001/graphql

      # 両サーバーの起動を待つ
      - name: Wait for Apollo Server
        run: pnpm exec wait-on tcp:4001

      - name: Wait for Next.js
        run: pnpm exec wait-on tcp:3001

      # テスト実行
      - name: Run tests
        run: pnpm test
        env:
          GRAPHQL_TEST_ENDPOINT: http://localhost:4001/graphql
