name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: sou-hyou
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Debug workspace information
      - name: Debug workspace
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Workspace info:"
          pnpm list --depth=0
          echo "Filter test:"
          pnpm --filter=web --dry-run dev || echo "Filter failed"

      # Copy test environment file
      - name: Setup test environment
        run: cp .env.test .env.local

      # Apollo Server 起動 (test environment)
      - name: Start Apollo Server
        working-directory: packages/server
        run: |
          echo "Starting Apollo Server on port 4001..."
          PORT=4001 pnpm dev > $GITHUB_WORKSPACE/apollo-server.log 2>&1 &
          echo $! > $GITHUB_WORKSPACE/apollo-server.pid
          sleep 3
          echo "Apollo Server logs:"
          cat $GITHUB_WORKSPACE/apollo-server.log
        env:
          NODE_ENV: test
          PORT: 4001
          MONGODB_URI: mongodb://admin:password@localhost:27017/sou-hyou-test?authSource=admin
          CORS_ORIGIN: http://localhost:3001

      # Next.js 起動 (test environment)
      - name: Start Next.js
        working-directory: apps/web
        run: |
          echo "Starting Next.js on port 3001..."
          PORT=3001 pnpm dev > $GITHUB_WORKSPACE/nextjs-server.log 2>&1 &
          echo $! > $GITHUB_WORKSPACE/nextjs-server.pid
          sleep 3
          echo "Next.js Server logs:"
          cat $GITHUB_WORKSPACE/nextjs-server.log
        env:
          NODE_ENV: test
          NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://localhost:4001/graphql

      # 両サーバーの起動を待つ
      - name: Wait for Apollo Server
        run: pnpm exec wait-on tcp:4001

      - name: Wait for Next.js
        run: pnpm exec wait-on tcp:3001

      # テスト実行
      - name: Run tests
        run: pnpm test
        env:
          GRAPHQL_TEST_ENDPOINT: http://localhost:4001/graphql

      # サーバー停止とログ出力
      - name: Stop servers and show final logs
        if: always()
        run: |
          echo "=== Final Apollo Server logs ==="
          [ -f $GITHUB_WORKSPACE/apollo-server.log ] && cat $GITHUB_WORKSPACE/apollo-server.log || echo "No Apollo Server log found"
          echo "=== Final Next.js logs ==="
          [ -f $GITHUB_WORKSPACE/nextjs-server.log ] && cat $GITHUB_WORKSPACE/nextjs-server.log || echo "No Next.js log found"
          
          echo "Stopping servers..."
          [ -f $GITHUB_WORKSPACE/apollo-server.pid ] && kill $(cat $GITHUB_WORKSPACE/apollo-server.pid) 2>/dev/null || true
          [ -f $GITHUB_WORKSPACE/nextjs-server.pid ] && kill $(cat $GITHUB_WORKSPACE/nextjs-server.pid) 2>/dev/null || true
